name: Deploy to EvenNode

on:
  push:
    branches: [main]

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: 'git.evennode.com'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      # Este paso tuve que hacerlo aqui debido a que Evennode tiene problemas al compilar
      - name: Build Next.js app
        run: |
          pnpm install
          pnpm build
          rm -rf .next/cache

      - name: Git credentials
        run: |
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_NAME }}"

      - name: Deploy to evennode.com
        run: |
          echo "${{ secrets.DOT_ENV_CONTENT }}" > .env
          git add .next .env -f
          git commit -m '[next production build]'
          git remote add evennode ${{ secrets.EVENNODE_REPO_URL }}
          git push evennode main -f
