name: Deploy to EvenNode

on:
  push:
    branches: [main]

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      # Este paso tuve que hacerlo aqui debido a que Evennode tiene problemas al compilar
      - name: Build Next.js app
        run: |
          pnpm install
          pnpm build
          rm -rf .next/cache
     
      - name: EvenNode Deploy
        uses: rodnye/evennode-deploy-action@v0.0.1-alpha
        with:
          key: ${{ secrets.EVENNODE_SSH_KEY }}
          git_url: ${{ secrets.EVENNODE_REPO_URL }}
          dot_env: ${{ secrets.DOT_ENV_CONTENT }}
          git_name: ${{ secrets.GIT_NAME }}
          git_email: ${{ secrets.GIT_EMAIL }}
          pre_commit_command: "git add .next -f"
